apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: haseweb-co-uk-ssl
spec:
  secretName: haseweb-co-uk
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: haseweb.co.uk
  dnsNames:
    - haseweb.co.uk
    - www.haseweb.co.uk
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - haseweb.co.uk
          - www.haseweb.co.uk
